name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  TEST: github-action

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      
    - 
      name: Build the Docker image
      run: docker build -t actions-testing:latest .
      
    -
      name: Run Tests
      run: docker run --rm actions-testing python -m pytest test_app.py
